### ISSUE TITLE
ChainID mismatch while running docker-compose run --rm samples node index.js

### ISSUE THREAD

**Issue by InitfortheTech** [Revolution-Populi/revpop-samples#5]
Dear community,

I have build/ran the core blockchain while following the instructions. Now i am trying to run all the samples while also following the instructions. However i can't seem to get past this one error: Error: Wrong blockchain network (chain ID mismatch)! Change it in the .env file.

I have changed the CHAIN_ID in the .env file to the one provided in the Genesis block:  3da3a128785cac2be918e634720795a1ca337a71533cb9f56e7a7391c5aa0614.

However i keep receiving this error. Maybe it has to do with the BLOCKCHAIN_URL? BLOCKCHAIN_URL should point to WS interface of the RevPop Blockchain node. How can i find out what to fill in under BLOCKCHAIN_URL? I have already tried, blockchain, localhost, 127.0.0.1 etc. 

Yours sincerely,

Initforthetech
![ChainIDMismatch](https://user-images.githubusercontent.com/89232235/131820192-f803bedd-475a-4dbc-91df-b561e2ea37e8.png)

**Comment by walteratwork** [comment]
Thanks for opening the issue!

Looks like the ChainID has been changed and your modification of the .env file didn't work because this file is not copied to the container by default.

The issue has been fixed - thanks!
Please pull the latest changes from the repository and rebuild the container:

```
git pull --ff
docker-compose down
docker-compose build --no-cache samples
```
